### ISSUE TITLE
fix your shit please

### ISSUE THREAD

**Issue by someone58198186911** [8dcc/source-netvar-dumper#1]
Thread 1 "hl2_linux" received signal SIGSEGV, Segmentation fault.
0xe5c984cf in netvars_dump () from /home/REDACTED/source-netvar-dumper/libnetvardumper.so
The program being debugged was signaled while in a function called from GDB.
GDB remains in the frame where the signal was received.
To change this behavior use "set unwindonsignal on".
Evaluation of the expression containing the function
(dlopen) will be abandoned.
When the function is done executing, GDB will silently stop.
$1 = 0x3a9159a0 "libnetvardumper.so: cannot open shared object file: No such file or directory"
[Inferior 1 (process 45616) detached]

**Comment by 8dcc** [comment]
Thank you for your constructive feedback. Should be fixed in 69fe7c713b25ccbbaa52dcf0bee20fa4fb88ad90.
